name: Build and Test

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
env:
  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Building
        run: yarn build

      - name: Testing
        run: yarn test
